import uuid from 'react-uuid';

export const PRODUCTS = [
    {
      id: 2133,
      price: 20,
      name: 'Tshirt-1',
      category: 'T-shirt',
      img: 'tshirt1.jfif',
      count: 100,
      sale: 80,
    },
    {
      id:243243,
      price: 20,
      name: 'Tshirt-2',
      category: 'T-shirt',
      img: 'tshirt2.jfif',
      count: 80,
      sale: 30,
    },
    {
      id:678654,
      price: 20,
      name: 'Tshirt-3',
      category: 'T-shirt',
      img: 'tshirt3.jpg',
      count: 67,
      sale: 21,
    },
    {
      id:243,
      price: 20,
      name: 'Tshirt-4',
      category: 'T-shirt',
      img: 'tshirt4.png',
      count: 90,
      sale: 79,
    },
    {
      id:234,
      price: 20,
      name: 'Tshirt-5',
      category: 'T-shirt',
      img: 'tshirt5.webp',
      count: 20,
      sale: 50,
    },
    {
      id:5324,
      price: 20,
      name: 'Tshirt-6',
      category: 'T-shirt',
      img: 'tshirt6.jfif',
      count: 50,
      sale: 23,
    },
    {
      id:5230,
      price: 20,
      name: 'Tshirt-7',
      category: 'T-shirt',
      img: 'tshirt8.jpg',
      count: 19,
      sale: 38,
    },
    {
      id:523,
      price: 20,
      name: 'Tshirt-8',
      category: 'T-shirt',
      img: 'tshirt1.jfif',
      count: 87,
      sale: 11,
    },
    {
      id:45645,
      price: 20,
      name: 'Tshirt-9',
      category: 'T-shirt',
      img: 'tshirt2.jfif',
      count: 100,
      sale: 14,
    },
    {
      id:2143,
      price: 20,
      name: 'Tshirt-10',
      category: 'T-shirt',
      img: 'tshirt3.jpg',
      count: 34,
      sale: 68,
    },
    {
      id:756,
      price: 20,
      name: 'Tshirt-11',
      category: 'T-shirt',
      img: 'tshirt4.png',
      count: 76,
      sale: 32,
    },
    {
      id:132,
      price: 20,
      name: 'Tshirt-12',
      category: 'T-shirt',
      img: 'tshirt5.webp',
      count: 10,
      sale: 10,
    },
    {
      id:634,
      price: 20,
      name: 'Tshirt-13',
      category: 'T-shirt',
      img: 'tshirt6.jfif',
      count: 18,
      sale: 49,
    },
    {
      id:2340,
      price: 20,
      name: 'Tshirt-14',
      category: 'T-shirt',
      img: 'tshirt8.jpg',
      count: 55,
      sale: 2,
    },
    {
      id:645,
      price: 20,
      name: 'Tshirt-15',
      category: 'T-shirt',
      img: 'tshirt1.jfif',
      count: 82,
      sale: 5,
    },
    {
      id:21342,
      price: 20,
      name: 'Tshirt-16',
      category: 'T-shirt',
      img: 'tshirt2.jfif',
      count: 27,
      sale: 19,
    },
    {
      id:5243,
      price: 20,
      name: 'Tshirt-17',
      category: 'T-shirt',
      img: 'tshirt3.jpg',
      count: 66,
      sale: 40,
    },
    {
      id:646,
      price: 20,
      name: 'Tshirt-18',
      category: 'T-shirt',
      img: 'tshirt4.png',
      count: 70,
      sale: 23,
    },
  ]